asottile/pyupgrade

pyupgrade.py, tests/pyupgrade_test.py
=> Prevent SyntaxError when rewriting dict((a, b)for a, b in y)

pyupgrade.py, tests/pyupgrade_test.py
Was curious what changes it would make on some large repository, found a syntax error afterwards!
=> Don't rewrite format literals with formats in formats

pyupgrade.py, tests/pyupgrade_test.py
From profiling, this improves runtime by ~16%
There are additional gains that could be made here by also combining the `unicode_literals` and `escape_sequences` fixers as well into this loop
=> Improve performance rewriting numeric literals

setup.py
The wheel package format supports including the license file. This is
done using the [metadata] section in the setup.cfg file. For additional
information on this feature, see:
https://wheel.readthedocs.io/en/stable/user_guide.html#including-license-files-in-the-generated-wheel-file
Helps project comply with its own license:
> The above copyright notice and this permission notice shall be
> included in all copies or substantial portions of the Software.
=> Include license file in the generated wheel package

setup.cfg
=> Include the LICENSE file in the sdist

pyupgrade.py, tests/pyupgrade_test.py
Taking a stab at this. Not sure if this is the best approach or if there are edge cases I missed. This is part of #59.
=> Rewrite six.b(...) to b-literal

pyupgrade.py, tests/pyupgrade_test.py
=> Rewrite `.encode('utf-8')` in some cases

pyupgrade.py, setup.cfg, tests/format_literals_test.py
this'll also improve performance of all runs of `pyupgrade` since it avoids an extra tokenize-untokenize \o/
=> Utilize rfind_string_parts to improve .format() rewrite

README.md, pyupgrade.py, tests/io_open_test.py
=> Rewrite `io.open` to `open`

azure-pipelines.yml, pyupgrade.py, tests/binary_literals_test.py, tests/encoding_cookie_test.py, tests/escape_sequences_test.py, tests/extra_parens_test.py, tests/format_literals_test.py, tests/long_literals_test.py, tests/octal_literals_test.py, tests/raw_unicode_literals_test.py, tests/unicode_literals_test.py
this will make it potentially easier to implement a `__future__` rewrite
=> Internally move to min_version over py#-plus

tests/main_test.py
@isidentical pointed out that [this](https://github.com/asottile/pyupgrade/blob/4fb4dd08da682c860c7e376dfa350c588843c2c0/pyupgrade.py#L108) looked strange.  I noticed that I didn't have a test failing when I removed `.encode('UTF-8')` so here's one
```
=================================== FAILURES ===================================
______________________ test_main_py27_syntaxerror_coding _______________________
tmpdir = local('/tmp/pytest-of-asottile/pytest-4/test_main_py27_syntaxerror_cod0')
def test_main_py27_syntaxerror_coding(tmpdir):
f = tmpdir.join('f.py')
f.write('# -*- coding: utf-8\nset((1, 2))\n')
>       assert main((f.strpath,)) == 1
E       AssertionError: assert 0 == 1
E        +  where 0 = main(('/tmp/pytest-of-asottile/pytest-4/test_main_py27_syntaxerror_cod0/f.py',)) …
```
=> Add failing test for py27 ast.parse(<unicode>)

pyupgrade.py
- `Token <-> str`: PEP 561 doesn't support single files otherwise mypy would have caught this. Also renamed a variable for clarity.
- `int -> bool`: `bool` is a subclass of `int` and there is no `strict-bool` setting
=> Fix type annotations

pyupgrade.py, tests/super_test.py
=> Rewrite old-style-class super calls

README.md
The backward-compatible usage of NamedTuple expects a list of 2-tuples, not a list of type annotated strings.
```
$ python3 -c "typing.NamedTuple('NT', [('a': int, 'b': Tuple[str, ...])])"
File "<string>", line 1
typing.NamedTuple('NT', [('a': int, 'b': Tuple[str, ...])])
^
SyntaxError: invalid syntax
```
See also https://docs.python.org/3/library/typing.html#typing.NamedTuple
=> Fix syntax error in NamedTuple example

pyupgrade.py, tests/typing_named_tuple_test.py, tests/typing_typed_dict_test.py
=> Ensure keys are non-keyword identifiers for TypedDict / NamedTuple

README.md, pyupgrade.py, tests/six_test.py
I was running pyupgrade and in a few repos it would remove every instance of six except his one. I figured this would be straightforward to rewrite as well. It's not a py3+ rewrite (so feel free to close) but but it would help remove more six code.
=> Rewrite `six.reraise(*sys.exc_info())`

README.md
https://github.com/asottile/pyupgrade/blob/master/pyupgrade/_plugins/typing_pep604.py#L90
Thanks for this great tool!
=> Document correct minimum version for PEP 604

pyupgrade/_plugins/open_mode.py, tests/features/open_mode_test.py
On `master`,
```python
with open('t.py', mode='r') as fd:
txt = fd.read()
```
won't get re-written
=> Rewrite open_mode even if mode is passed by name

pyupgrade/_main.py, pyupgrade/_plugins/oserror_aliases.py, tests/features/fstrings_test.py
Working at the AST level meant we only handled a small subset of Python when generating f-strings. By extracting the original code as a string we can handle many more cases.
~~A disadvantage of this approach is that it requires Python ≥ 3.8 for `ast.expr.end_lineno`, `ast.expr.end_col_offset`.~~ This now uses the token stream like everything else, avoiding that requirement.
=> Use original source when building f-strings

README.md, pyupgrade/_data.py, pyupgrade/_plugins/universal_newlines_to_text.py, tests/features/universal_newlines_to_text_test.py
=> upgrade subprocess.run(universal_newlines=True) to subprocess.run(text=True) in --py37-plus

README.md, pyupgrade/_plugins/unpack_list_comprehension.py, tests/features/unpack_list_comprehension_test.py
=> Use generator to unpack list comprehension

README.md, pyupgrade/_plugins/c_element_tree.py, tests/features/c_element_tree_test.py
closes #311 
there's not currently a `--py33-plus` flag, should that be added or is `--py36-plus` OK?
=> rewrite cElementTree to ElementTree

pyupgrade/_token_helpers.py, tests/features/six_test.py
xref https://github.com/asottile/pyupgrade/pull/364#issuecomment-845651933
> @MarcoGorelli btw, if you find the open wip PRs interesting feel free to take them over -- haven't had time to finish them up
=> fix six.with_metaclass and trailing commas

pyupgrade/_main.py, tests/features/fstrings_test.py, tests/features/typing_named_tuple_test.py, tests/features/typing_typed_dict_test.py
=> Upgrade to f-string get broken for Py3.6 in case await keyword is in

pyupgrade/_plugins/default_encoding.py, tests/features/default_encoding_test.py
=> f"wat".encode("utf-8") can also be rewritten to remove the encoding

pyupgrade/_plugins/generator_expressions_pep289.py, tests/features/generator_expressions_pep289_test.py
=>  async generator breakage

pyupgrade/_ast_helpers.py, pyupgrade/_main.py, pyupgrade/_plugins/generator_expressions_pep289.py, tests/features/generator_expressions_pep289_test.py
=> dont do generator rewrite if list comp contains await

README.md, pyupgrade/_data.py, pyupgrade/_plugins/six_simple.py, tests/features/six_simple_test.py
=> rewrite six.moves.range

tests/features/pep584_test.py
The test I'd added in https://github.com/asottile/pyupgrade/pull/505 didn't, at the time, fail on master - sorry about that, I should've done "red green refactor"
To make sure the bug doesn't appear again, I've added a test which would've failed in that version of pyupgrade:
```console
(venv39) marcogorelli@OVMG025 pyupgrade-dev % git checkout v2.23.0 -- pyupgrade       
(venv39) marcogorelli@OVMG025 pyupgrade-dev % pytest tests/features/pep584_test.py -qq
..........F                                                                                                                                [100%]
==================================================================== FAILURES ==================================================================== …
```
=> Add extra test for pep584 with comma inside comprehension

pyupgrade/_plugins/percent_format.py, tests/features/percent_format_test.py
=> don't rewrite %-format with width+s

README.md, pyupgrade/_plugins/versioned_branches.py, tests/features/versioned_branches_test.py
Fix #488
It should cover Python 3.x branches (where x is >=0) using operators `<`, `<=`, `>`, `>=`, and assuming
that an `else` statement exists.
A couple remarks:
- this is my very first contribution to anything that uses `ast`, so I'm kind of astonished that my own tests are passing, but I'll gladly take any suggestions on how to make this better
- I ended up kinda "hacking" existing functions (namely `_fix_py3_block`, `_fix_py3_block_else` and `_fix_py2_block`) in the sense that I'm using them without modifications in a different fashion compared to their original intended usage. I suppose they ought to be renamed to better reflect what they actually do here (fix and if/else block and keep the top or lower half ?), but I leave this as a question to the maintainer
- I didn't cover the …
=> ENH: expand versioned_branches feature to Python 3 minor version comparison (<, >, <=, >= with else)

tests/features/versioned_branches_test.py
Followup to #530, thanks to [a comment from @graingert](https://github.com/asottile/pyupgrade/commit/31546d2cdf4a7647df46b0e9c4b771efe123ea3b#r56396117)
Actually the bug now fails, revealing a bug in #530 ? I'll try to fix this promptly
=> BUG: fix broken tests for versioned_branches feature

pyupgrade/_main.py, pyupgrade/_plugins/percent_format.py, pyupgrade/_string_helpers.py, tests/features/format_literals_test.py, tests/features/fstrings_test.py, tests/features/percent_format_test.py
=> handle named escape sequences in format upgrades

README.md
The diff format has been used for most new features and I find it much easier to read.
=> Rewrite docs examples with commented code to use diffs

pyupgrade/_plugins/native_literals.py, pyupgrade/_token_helpers.py, tests/features/native_literals_test.py
resolves #649
I unfortunatelly have to check `node.func.id == 'bytes'` twice, to later narrow it down so that the Call name is `bytes` **while** the arg is `ast.Bytes`. But for some reason mypy is mad at the second check with:
```
pyupgrade/_plugins/native_literals.py:56: error: "expr" has no attribute "id"
Found 1 error in 1 file (checked 95 source files)
```
could you give me a hint what's wrong there?
also not sure if the rename of the `_fix_native_str` function is okay since it now also handles bytes?
=> rewrite bytes(b'foo') to b'foo'

pyupgrade/_plugins/imports.py, tests/features/import_removals_test.py
reported by `bork` in [discord](https://discord.com/channels/576802746850869258/747133137804591156/1001211167114530856)
when using `--py38-plus` (or any other mode which is a superset of `py3-plus`), most of the imports were not removed
```python
$ cat t.py
from __future__ import print_function
pass
$ pyupgrade --py38-plus t.py
$ cat t.py
from __future__ import print_function
pass
$ pyupgrade --py3-plus t.py
Rewriting t.py
$ cat t.py
pass
```
introduced by refactoring in https://github.com/asottile/pyupgrade/commit/4775ca8ad7cac72dc8dd5c6bcd29defd2d375cbb
added a test-case
=> fix imports removal not including rules from previous versions

pyupgrade/_plugins/typing_classes.py, tests/features/typing_classes_test.py
This ensures that comments which appear around `TypedDict`s and `NamedTuple`s that are converted to class style are preserved.
The layout of the comments in the new code isn't perfect, however that's relatively easy for the user to fix manually afterwards. This is the main negative of this approach. There are things which we could do here (such as looking at the previous/next tokens and comments' tokens to try to line them up), however IMO having the comments with slight alignment issues is useful enough even with this limitation.
I've added tests based on the cases I'm aware of, but very open to adding more tests if there are cases you're concerned about which are not covered here.
Fixes https://github.com/asottile/pyupgrade/issues/497
Fixes …
=> Implement preservation of comments "within" typing classes

pyupgrade/_plugins/typing_classes.py, tests/features/typing_classes_test.py
Hi, I appreciate your work on this project. Our transition to Python 3.10 was seamless thanks to it.
There was a problem running pyupgrade on our codebase.
The following statement was acceptable:
`D = typing.TypedDict("D", {"a": typing.Literal["b", "c"]})`
But, the these statements raise a `NotImplementedError: Constant(value=*)` error, causing Pyupgrade to crash:
- `D = typing.TypedDict("D", {"a": typing.Literal[1, 2]})`
- `D = typing.TypedDict("D", {"a": typing.Literal[b"b", b"c"]})`
=> Add ast.Bytes in typing_classes _unparse

setup.cfg
tokenze-rt will remove python2-compat parsing
=> limit tokenize-rt to <4 before breaks

pyupgrade/_plugins/set_literals.py, tests/features/set_literals_test.py
there is a comment in the code about this causing a SyntaxError but as far as I can tell that is incorrect
=> rewrite set((\n))

pyupgrade/_plugins/typing_pep646_unpack.py, tests/features/typing_pep646_unpack_test.py
=> Add PEP646 Unpack plugin

pyupgrade/_plugins/typing_pep604.py, tests/features/typing_pep604_test.py
`Optional["ForwardRef"]` currently requires two `pyupgrade` calls to be fully rewritten. Here's a minimal example:
```shell
$ echo "from __future__ import annotations; from typing import Optional; x: Optional['str']" > repro.py
$ pyupgrade --py39-plus repro.py; cat repro.py
Rewriting repro.py
from __future__ import annotations; from typing import Optional; x: Optional[str]
$ pyupgrade --py39-plus repro.py; cat repro.py
Rewriting repro.py
from __future__ import annotations; from typing import Optional; x: str | None
```
The problem here is that `typing_pep604.py` bails if it encounters a forward annotation (https://github.com/asottile/pyupgrade/issues/567). This PR adjusts the check to guess ahead if annotations will be dequoted by `typing_pep563.py`. 
I guess there's an argument to be …
=> Fix `Optional["ForwardRef"]` rewriting

README.md, pyupgrade/_plugins/datetime_utc_alias.py, tests/features/datetime_utc_alias_test.py
Rewrite:
```python
import datetime
datetime.timezone.utc
```
to alias:
```python
import datetime
datetime.UTC
```
in Python >= 3.11.
Fixes: #755
=> rewrite to datetime.UTC

pyupgrade/_plugins/typing_classes.py, tests/features/typing_classes_test.py
Fixes #766
Cheers from the discord server!
=> Add support for BinOr typing union syntax

README.md, pyupgrade/_plugins/shlex_join.py, tests/features/shlex_join_test.py
=> automatically rewrite to shlex.join in --py38-plus

pyupgrade/_plugins/unittest_aliases.py, tests/features/unittest_aliases_test.py
Closes #749.
I saw that #759 was closed without actually fixing the issue.
=> fix bug when rewriting deprecated unittest functions

README.md, pyupgrade/_ast_helpers.py, pyupgrade/_plugins/constant_fold.py, pyupgrade/_plugins/exceptions.py, pyupgrade/_plugins/six_simple.py, pyupgrade/_token_helpers.py, tests/features/constant_fold_test.py
=> constant fold isinstance / issubclass / except

README.md, pyupgrade/_data.py, pyupgrade/_plugins/defauldict_lambda.py, tests/features/defauldict_lambda_test.py
Fixes #899 
I left a few comments with some questions.
=> Defaultdict lambdas

pyupgrade/_token_helpers.py, tests/features/exceptions_test.py
resolves #932
there's not a great way to keep the comments so it's just easier to remove them.  the programmer can add them back if desired 🤷
=> handle constant folding with comments on multilines better

pyupgrade/_plugins/imports.py
Following https://github.com/asottile/reorder-python-imports/pull/380
=> Regenerate typing import replacements using latest reorder-python-imports

pyupgrade/_plugins/typing_pep646_unpack.py, tests/features/typing_pep646_unpack_test.py
needs https://github.com/python/mypy/issues/12280 first though
=> rewrite pep 646 Unpack to splat in `*args`

pyupgrade/_plugins/dict_literals.py, pyupgrade/_plugins/set_literals.py, tests/features/dict_literals_test.py, tests/features/set_literals_test.py
this can change the syntax by doubling the curly braces
resolves #976
=> prevent dict/set rewrite directly in f-string placeholder

pyupgrade/_string_helpers.py, setup.cfg, tests/main_test.py
=> fix named escapes in FSTRING_MIDDLE

pyupgrade/_plugins/default_encoding.py, pyupgrade/_token_helpers.py, tests/features/default_encoding_test.py
=> fix search for .encode(...) call with 3.12+ f-string tokens
