asottile/pyupgrade

- pyupgrade.py
- tests/pyupgrade_test.py
> Remove trailing commas that would cause SyntaxErrors

- pyupgrade.py
- tests/pyupgrade_test.py
> Don't rewrite dict(..., kwarg=...)

- README.md
- pyupgrade.py
- tests/pyupgrade_test.py
> Convert long literals

- README.md
- pyupgrade.py
- tests/pyupgrade_test.py
> Automatically upgrade octal literals

- README.md
- pyupgrade.py
- tests/pyupgrade_test.py
> Implement rewriting of simple f-strings

- README.md
Committed via https://github.com/asottile/all-repos
> sha -> rev (pre-commit 1.7.0+)

- appveyor.yml
- tests/pyupgrade_test.py
Committed via https://github.com/asottile/all-repos
> Use python3.7 in appveyor

- pyupgrade.py
- tests/pyupgrade_test.py
> Handle interspersed escaped format tokens

- pyupgrade.py
- tests/pyupgrade_test.py
CC @anntzer -- thanks again for the report
Relates to #50
> Don't rewrite super() inside of a comprehension

- README.md
- pyupgrade.py
- tests/pyupgrade_test.py
> Add --keep-percent-format

- README.md
- pyupgrade.py
- tests/pyupgrade_test.py
> Fix invalid escape sequences

- pyupgrade.py
- tests/pyupgrade_test.py
> Don't turn escaped crlfs into raw strings

- tests/pyupgrade_test.py
See https://github.com/boxed/mutmut
> Add some more tests for edge cases found by mutmut

- pyupgrade.py
- tests/pyupgrade_test.py
> Rewrite six.raise_from and six.reraise

- pyupgrade.py
- tests/pyupgrade_test.py
> Add an alignment spec if there is a width spec

- pyupgrade.py
- tests/pyupgrade_test.py
> Don't raw-string with escaped newlines

- README.md
- pyupgrade.py
- tests/pyupgrade_test.py
> Auto fix ur'...' literals

- pyupgrade.py
- tests/pyupgrade_test.py
> Fix regression for unicode string fixing

- pyupgrade.py
- tests/pyupgrade_test.py
> Remove six.Iterator (py3+) and combine six fix with class fix

- README.md
- pyupgrade.py
- tests/pyupgrade_test.py
> Implement rewrite of `is <constant literal>`

- pyupgrade.py
- tests/pyupgrade_test.py
> Fix bug with extraneous parens and coroutines

- pyupgrade.py
- tests/pyupgrade_test.py
> Fix with_metaclass(...) rewrite without extra base classes

- pyupgrade.py
- tests/pyupgrade_test.py
> Don't crash on bracketed f-strings

- pyupgrade.py
- tests/pyupgrade_test.py
> Also check for [ further into the format

- README.md
- pyupgrade.py
- tests/pyupgrade_test.py
> Rewrite invalid \N escape sequences

- pyupgrade.py
- tests/pyupgrade_test.py
> Rewrite native literals in py3-plus mode

- pyupgrade.py
- tests/pyupgrade_test.py
> Also make TokenError a noop in more places

- pyupgrade.py
- tests/pyupgrade_test.py
> Skip rewriting six.thing(*a)

- .pre-commit-config.yaml
- tests/pyupgrade_test.py
(Not sure if this was omitted intentionally)
> Enable add-trailing-comma

- pyupgrade.py
- tests/pyupgrade_test.py
> Properly remove indented decorators

- pyupgrade.py
- tests/pyupgrade_test.py
> rewrite  six `if py2` blocks

- pyupgrade.py
- tests/pyupgrade_test.py
Resolves #102 
Known issues (?):
* Removes newlines from between for and yield
* triple-quoted strings prevent the upgrade
Another way to handle loop body would be to take everything, replace the yield, adjust indent. I think it would simplify code a little. Tell me what do you think :)
> Implement 'yield from collection' formatter

- README.md
- pyupgrade.py
- tests/pyupgrade_test.py
> Also rewrite sys.version_info blocks

- pyupgrade.py
- tests/pyupgrade_test.py
> Fix broken f-strings + named / auto out-of-order f-strings

- pyupgrade.py
- tests/pyupgrade_test.py
> don't rewrite six attributes with parens

- pyupgrade.py
- tests/pyupgrade_test.py
> Fix yield from for async functions

- README.md
- pyupgrade.py
- tests/pyupgrade_test.py
Attempts to address part of #141
> Rewrite some OSError aliases

- README.md
- setup.cfg
- tests/long_literals_test.py
- tests/octal_literals_test.py
> Also fix octal / long literals in python 3

- pyupgrade.py
- tests/set_literals_test.py
> Fix stray trailing comma in set literal rewrite

- README.md
- pyupgrade.py
- tests/native_literals_test.py
> Rewrite `str()` as `''`

- README.md
- pyupgrade.py
- tests/oserror_aliases_test.py
> Rewrite more OSError aliases

- pyupgrade.py
- tests/oserror_aliases_test.py
> Rewrite multiple OSError aliases in the same `except` block

- pyupgrade.py
- tests/fstrings_test.py
> Fix invalid f-string conversion attempt

- pyupgrade.py
- tests/six_test.py
> Special-case `next(six.iter*())` rewrite

- README.md
- pyupgrade.py
> Rewrite six.int2byte

- pyupgrade.py
- tests/six_test.py
> Fix list index out of range in next() rewriter

- README.md
- pyupgrade.py
- tests/six_test.py
> six.get_unbound_method is not a thing

- pyupgrade.py
- tests/binary_literals_test.py
> Add exclusion for extended unicode escapes

- README.md
- pyupgrade.py
- tests/import_removals_test.py
> Also remove unneeded imports from six / six.moves / builtins

- README.md
- pyupgrade.py
- tests/native_literals_test.py
- tests/six_test.py
> six: ensure_str / ensure_binary / ensure_text of a literal string

- pyupgrade.py
- tests/six_test.py
> Fix error on six.reraise(2, args)

- pyupgrade.py
- tests/native_literals_test.py
> Convert six.text_type('foo') in one pass

- pyupgrade.py
- tests/six_test.py
> Resolve with_metaclass(M, object) in one pass

- pyupgrade.py
- tests/open_mode_test.py
> Remove redundant open modes

- pyupgrade.py
- tests/open_mode_test.py
I noticed I missed a few in #263
> Add some additional modes I missed

- .pre-commit-config.yaml
- pyupgrade.py
- setup.cfg
[python 3 statement - 3.6.0](https://github.com/asottile/scratch/wiki/python-3-statement#360)
(due to broken `NamedTuple` in 3.6.0)
> pyupgrade: python3.6.1+

- README.md
Document changes made for #249
> Document overwriting of open modes

- pyupgrade.py
- tests/format_literals_test.py
- tests/fstrings_test.py
- tests/percent_format_test.py
> Avoid crashing / incorrect behaviour on \N

- README.md
- pyupgrade.py
- tests/fstrings_test.py
- tests/typing_named_tuple_test.py
- tests/typing_typed_dict_test.py
> implement  TypedDict / NamedTuple rewrite

- pyupgrade.py
- tests/typing_typed_dict_test.py
> Fix small oversight in Slice of typing classes

- pyupgrade.py
```console
$ echo -n 'import sys' | ~/.pyenv/versions/py3.6.5/bin/tokenize-rt /dev/stdin
1:0 NAME 'import'
?:? UNIMPORTANT_WS ' '
1:7 NAME 'sys'
2:0 ENDMARKER ''
```
> Update comment about missing NEWLINE

- README.md
- pyupgrade.py
- tests/metaclass_type_test.py
(Needs some more work to get tests to pass)
Resolves #288
> Rewrite __metaclass__ = type

- README.md
- pyupgrade.py
- tests/default_encoding_test.py
- tests/io_open_test.py
- tests/main_test.py
- tests/metaclass_type_test.py
- tests/native_literals_test.py
- tests/new_style_classes_test.py
- tests/no_arg_decorators_test.py
- tests/open_mode_test.py
- tests/oserror_aliases_test.py
- tests/six_test.py
- tests/super_test.py
- tests/versioned_branches_test.py
- tests/yield_from_test.py
> Rewrite @functools.lru_cache()

- README.md
- pyupgrade.py
- tests/mock_test.py
> Rewrite mock to unittest.mock

- pyupgrade.py
- tests/yield_from_test.py
Resolves #216
thanks to @atugushev for the initial implementation and many of the tests here
> fix yield from

- pyupgrade.py
- tests/yield_from_test.py
> Fix deletions of variables

- pyupgrade.py
- tests/open_mode_test.py
> don't rewrite open mode with >2 positional args

- README.md
- pyupgrade.py
- tests/mock_test.py
> Add --keep-mock option

- pyupgrade.py
- tests/versioned_branches_test.py
> fix py2 branches with multiple internal blocks

- pyupgrade.py
- tests/format_literals_test.py
> leave f'string'.format(...) alone

- pyupgrade.py
- tests/six_test.py
> fix any call with *sys.exc_info()

- pyupgrade.py
- tests/default_encoding_test.py
> fix off-by-one in encode() call fixer

- pyupgrade.py
- tests/six_test.py
> parenthesize expressions when replacing six calls when needed

- README.md
- pyupgrade.py
- tests/generic_types_test.py
- tests/imports_future_test.py
- tests/unicode_literals_test.py
See #343
this is just the start of the rewriting here, still need to do a lot with import renaming
> Add --py39-plus and pep585 rewriting

- pyupgrade.py
- tests/main_test.py
> add test for --py39-plus

- README.md
- pyupgrade/_plugins/typing_text.py
- tests/features/typing_text_test.py
> replace typing.Text with str

- pyupgrade/_main.py
- pyupgrade/_plugins/typing_pep604.py
- pyupgrade/_token_helpers.py
- tests/features/typing_pep604_test.py
- tests/main_test.py
> rewrite pep604 (+ add --py310-plus)

- README.md
- pyupgrade/_plugins/lru_cache.py
- tests/features/lru_cache_test.py
Contributing a plugin for https://github.com/asottile/pyupgrade/issues/348
> lru_cache(maxsize=None) => cache

- pyupgrade/_plugins/typing_pep604.py
- tests/_plugins/typing_pep604_test.py
- tests/features/typing_pep604_test.py
> fix nested union replaces

- pyupgrade/_plugins/typing_pep563.py
- tests/features/typing_pep563_test.py
closes #255  (at least, attempts to)
> quoted annotations + `from __future__ import annotations` 

- pyupgrade/_main.py
Started working on #381 and noticed this, keeping to a separate PR as it's just a clean up
> CLN - use dict comprehension in _format_params

- pyupgrade/_main.py
- tests/features/typing_typed_dict_test.py
>  Support translating TypedDict's with 'total' option

- README.md
- pyupgrade/_main.py
- pyupgrade/_plugins/typing_pep563.py
- tests/features/typing_pep563_test.py
> move pep563 rewrite to py311

- pyupgrade/_plugins/universal_newlines_to_text.py
Hi Anthony,
During stream yesterday you said that it might be better to do this by just replacing that one token - is this what you meant?
> CLN only replace argument token

- pyupgrade/_main.py
- tests/main_test.py
> don't crash on --py311-plus

- pyupgrade/_plugins/identity_equality.py
Committed via https://github.com/asottile/all-repos
> Use more inclusive language

- pyupgrade/_plugins/pep584.py
- tests/features/typing_584_test.py
> Rewrite merge dictionaries

- README.md
I forgot to update the README in #436, sorry about that
> Note pep584 change in README

- README.md
- pyupgrade/_plugins/generator_expressions_pep289.py
- pyupgrade/_plugins/unpack_list_comprehension.py
- pyupgrade/_token_helpers.py
- tests/features/generator_expressions_pep289_test.py
> Use generator expressions in some built-in functions

- pyupgrade/_plugins/generator_expressions_pep289.py
- tests/features/generator_expressions_pep289_test.py
> check argument count for generator rewrite

- pyupgrade/_plugins/generator_expressions_pep289.py
- tests/features/generator_expressions_pep289_test.py
closes #452 
(will check this more carefully in ~1 hour)
> Remove trailing comma after removed list comp

- README.md
- pyupgrade/_plugins/generator_expressions_pep289.py
- pyupgrade/_plugins/unpacking_argument_list_comprehensions.py
- pyupgrade/_token_helpers.py
- tests/features/unpacking_argument_list_comprehensions_test.py
closes #257 
@graingert any edge cases to consider?
> unpack argument list comprehensions

- pyupgrade/_plugins/generator_expressions_pep289.py
- tests/features/generator_expressions_pep289_test.py
> revert string join for potential perf reasons

- pyupgrade/_plugins/open_mode.py
- tests/features/open_mode_test.py
> replace open modes with string flags

- pyupgrade/_token_helpers.py
- tests/features/versioned_branches_test.py
> fix elif -> else when indented

- pyupgrade/_plugins/metaclass_type.py
- tests/features/metaclass_type_test.py
> fix __metaclass__ = type replacement without extra newline

- pyupgrade/_main.py
- setup.cfg
Committed via https://github.com/asottile/all-repos
> stricter mypy settings

- pyupgrade/_plugins/lru_cache.py
- tests/features/lru_cache_test.py
xref https://github.com/asottile/pyupgrade/pull/393#discussion_r572895574 (@mxr is this what you were suggesting?)
> Rewrite lru_cache with maxsize=None and typed=False

- README.md
- pyupgrade/_plugins/type_of_primitive.py
- tests/features/type_of_primitive_test.py
> replace type(''), type(b''), and type(0) with str, bytes, and int

- pyupgrade/_plugins/pep584.py
- tests/features/pep584_test.py
> fix bug in merge dicts: look for comma backwards

- pyupgrade/_main.py
- tests/features/typing_typed_dict_test.py
> correctly compute indent for typeddict after dedent

- pyupgrade/_ast_helpers.py
- pyupgrade/_plugins/generator_expressions_pep289.py
- pyupgrade/_plugins/unpack_list_comprehension.py
- pyupgrade/_plugins/unpacking_argument_list_comprehensions.py
- tests/features/unpack_list_comprehension_test.py
- tests/features/unpacking_argument_list_comprehensions_test.py
> fix unpacking or splatting async generators

- README.md
- pyupgrade/_plugins/unittest_aliases.py
- tests/features/unittest_aliases_test.py
> Rewrite unittest deprecated aliases

- pyupgrade/_plugins/legacy.py
- tests/features/super_test.py
> don't rewrite old-super for staticmethods

- pyupgrade/_plugins/typing_pep604.py
- tests/features/typing_pep604_test.py
> prevent rewriting union types with forward annotations

- README.md
- pyupgrade/_data.py
- pyupgrade/_plugins/abspath_file.py
- tests/features/abspath_file_test.py
> rewrite abspath(__file__) to __file__ in py39+

- pyupgrade/_plugins/six_calls.py
- tests/features/six_test.py
> don't rewrite six.reraise with named args

- README.md
> Use diff syntax in more places in the docs

- pyupgrade/_plugins/subprocess_run.py
- tests/features/universal_newlines_to_text_test.py
> dont rewrite universal_newlines if text or **kwargs present 

- pyupgrade/_main.py
- pyupgrade/_plugins/fstrings.py
- pyupgrade/_string_helpers.py
- tests/features/format_literals_test.py
- tests/features/fstrings_test.py
- tests/string_helpers_test.py
this significantly improves performance, but causes %-format to need two rounds to resolve -- I think that's probably fine and could be fixed in the future
> convert fstring rewriter to a plugin

- pyupgrade/_plugins/subprocess_run.py
- tests/features/universal_newlines_to_text_test.py
> rewrite check_output(...) universal_newlines -> text

- README.md
- pyupgrade/_plugins/typing_pep563.py
- tests/features/typing_pep563_test.py
> Do not remove quoted annotations on 3.11

- pyupgrade/_plugins/open_mode.py
- tests/features/open_mode_test.py
Co-Authored-By: Ali Hamdan <ali.hamdan.dev@gmail.com>
resolves #273
> converge open modes of io.open in one pass

- tests/features/import_replaces_test.py
Co-Authored-By: ptmcg <ptmcg@austin.rr.com>
> add more tests for import rewriting

- pyupgrade/_plugins/collections_abc.py
- tests/features/collections_abc_test.py
Co-Authored-By: ptmcg <ptmcg@austin.rr.com>
> rewrite collections.Name to collections.abc.Name

- pyupgrade/_plugins/legacy.py
- tests/features/super_test.py
> Rewrite 2-arg super call in nested class

- setup.cfg
redo of #715 but correct this time
> oops, I meant <5

- pyupgrade/_plugins/imports.py
- tests/features/import_replaces_test.py
> fix import rewriting with aliases in multi-from

- tests/features/six_test.py
seems it just works now in 3.12
resolves #572
> add tests for rewriting within fstrings

- pyupgrade/_plugins/versioned_branches.py
- tests/features/versioned_branches_test.py
> handle more flavors of versioned branches

- pyupgrade/_string_helpers.py
- tests/features/format_literals_test.py
> fix string formatting with named escape adjacent to placeholder

- pyupgrade/_data.py
- pyupgrade/_plugins/oserror_aliases.py
> also rewrite os.error -> OSError

- README.md
Re: https://docs.python.org/3/library/asyncio-exceptions.html#asyncio.TimeoutError
> README: Fix asyncio.Timeout -> asyncio.TimeoutError typo

- pyupgrade/_plugins/shlex_join.py
- tests/features/shlex_join_test.py
> only replace to shlex.join if joined with a space

- pyupgrade/_plugins/versioned_branches.py
- tests/features/versioned_branches_test.py
> Rewrite `version_info[0]` and `version_info.major`
